### ISSUE TITLE
make it possible to generate classes that are more than 2 characters long?

### ISSUE THREAD

**Issue by vesper8** [sndyuk/mangle-css-class-webpack-plugin#1]
Hi @sndyuk

First of all thanks a lot for making this. I'm finding it very useful and it's just what I need to obfuscate projects that make use of Tailwind CSS

However right now I'm running into a problem where it's throwing the `Maximum class names generated. Change the generator` error. I see this is happening because the current logic prevents classnames from being more than 2 characters long. This would be easily remedied if you could go up to 3 characters.. it would be nice if this was configurable but really a simple patch that would allow up to 3 characters once you've exhausted all possible 2-character combinations would solve the problem. I don't see why add this artification limitation, most projects won't need to go to 3 characters but if you do then why prevent it?

If you could release this small patch that would be greatly appreciated!

Thanks!

**Comment by sndyuk** [comment]
@vesper8 Thank you for the suggestion! It's been released as v4.0.5.

**Comment by vesper8** [comment]
awesome! thank you!!
