### ISSUE TITLE
Thank you for made this

### ISSUE THREAD

**Issue by IRediTOTO** [sndyuk/mangle-css-class-webpack-plugin#15]
Hi, can I get a favor to send you a coffee by Paypal? 
Btw, I am  using this setup with tailwind classname. Is there any way to regex without `tw-` ?
```
 new MangleCssClassPlugin({
        classNameRegExp:
          '((hover|focus|xs|md|sm|lg|xl)[\\\\]*:)*tw-[a-z_-][a-zA-Z0-9_-]*',
        ignorePrefixRegExp: '((hover|focus|xs|md|sm|lg|xl)[\\\\]*:)*',
        log: true,
      })
```

**Comment by sndyuk** [comment]
@IRediTOTO Thank your saying that :)
I don't have any idea making it work without any specific prefix like `tw-` unfortunately. Otherwise the plugin breaks code.

**Comment by IRediTOTO** [comment]
I didn't learn about web pack so i can't help you :c 
But here is my idea, maybe it can help:
You search in entry JS file, right ? 

```
import Link from 'next/link'
import Nav from '../components/nav'

export default function IndexPage() {
  return (
    <div>
      <Nav />
      <div className="tw-py-20">
        <h1 className="hover:tw-text-red-800 tw-text-5xl tw-text-center tw-text-accent-1">
          Next.js + Tailwind CSS
        </h1>
        <Link href="/sample" as="/sample">
          <a className="tw-px-5 tw-py-5 tw-text-blue-800">Click me</a>
        </Link>
      </div>
    </div>
  )
}
```
I found this regex `(?<=className=")(.*)(?=")`
It will get `tw-py-20` in code `className="tw-py-20"`
If have many class name, can use split(" ") to split class name. I think :D 
Sorry If you knew that. I am just low level dev.
