### ISSUE TITLE
missing scan some class name

### ISSUE THREAD

**Issue by IRediTOTO** [sndyuk/mangle-css-class-webpack-plugin#26]
Hi, I have a component use react portal, but class name wasn't scanned.
Others component is fine. Did you face with this error? 
 If I remove mangle-css-class config, tailwind will work fine, no error (using tailwind jit mode)
![image](https://user-images.githubusercontent.com/15695252/121110858-276b4f80-c838-11eb-8466-9dac0800ec00.png)

**Comment by IRediTOTO** [comment]
Error maybe from use React supense

**Comment by sndyuk** [comment]
Hi @IRediTOTO, that class names on the DOM is created dynamically? What framework do you use to generate the DOM? or Is this a static file?

**Comment by sndyuk** [comment]
> tailwind jit mode

Oh, does it means the class name is created dynamically on runtime? It sounds that the plugin cannot handle it.

**Comment by IRediTOTO** [comment]
yes you can with god regex :D It work pretty well with me now. regex can scan []

**Comment by IRediTOTO** [comment]
Your pack is very usefull, don't know why people not use it. Thank you for made it.
