### ISSUE TITLE
i dont understand how to use it

### ISSUE THREAD

**Issue by guoris** [sndyuk/mangle-css-class-webpack-plugin#32]
I need help to use this, on youtube there is no video to guide me, could you help me?

**Comment by semdzh** [comment]
> I need help to use this, on youtube there is no video to guide me, could you help me?

hi @guoris,
Where do you want to use it? Please give me more information, maybe I can help. I've been trying to figure this plugin out for days.

**Comment by guoris** [comment]
I want to use it in css html classes, but I don't understand how to use it, I need you to help me, pls

**Comment by semdzh** [comment]
> 
> 
> I want to use it in css html classes, but I don't understand how to use it, I need you to help me, pls

Do you just have a website based on html/css or are you using a framework or library (react, vue)?

**Comment by guoris** [comment]
I have a website based on html and css

**Comment by guoris** [comment]
do you have discord? and we talk over there

**Comment by semdzh** [comment]
> I have a website based on html and css

If you have a simple html/css website, you should use [posthtml](https://github.com/semdzh/posthtml-minify-classnames), it's much easier to implement.

**Comment by guoris** [comment]
I already downloaded it, I don't understand how to use it, how do I run it?
