### ISSUE TITLE
Bulma css support

### ISSUE THREAD

**Issue by IRediTOTO** [sndyuk/mangle-css-class-webpack-plugin#33]
Hi, I am use regex like this 
```
classNameRegExp: (bm-[a-zA-Z-]([a-zA-Z0-9-]*([\\\\\\\\]*(\\%|\\#|\\.|\\[|\\]))*)*',
```
but they missing classname on css files
example
the class name like this will be missed
```
.button.is-primary {....};
```
it will be transformed to:
```
a.b {...};  // lost dot '.' charactor in css file. 
```
in HTML everything look fine
Can you please take a look? Is this error come from my regex ? I tried to test but regex is fine
![image](https://user-images.githubusercontent.com/15695252/137602511-c0e72868-c885-4238-b2a6-70d19272636b.png)

**Comment by sndyuk** [comment]
@IRediTOTO It looks weird. Can I get the `log` from the plugin?

P.S `\\\\\\\\` should be `\\\\`.
ref. `If you want to use the back slash \ on the regexp, use [\\\\]* to match class names contained both JS(\\\\) and CSS(\\\\\\\\\\\\\\\\).` (README.md)

**Comment by IRediTOTO** [comment]
@sndyuk  thank you so much 💯
