### ISSUE TITLE
Also mangling html tags where it should not

### ISSUE THREAD

**Issue by squareloop1** [sndyuk/mangle-css-class-webpack-plugin#37]
It seems like html tags also get mangled when caught by the regex. I am currently trying to mangle css classes from quasar framework with this regex:

`classNameRegExp: '(q-)[a-zA-Z-][a-zA-Z0-9-]*',`

I even tried negative and positive lookbehinds in the regex to exclude html tags specifically (`(?<!\/|\<)q-[a-zA-Z-][a-zA-Z0-9-]*`). Sadly without any success. It seems like the mangling process is somewhere before custom vue components get resolved to their corresponding html tags. I don't know why a regex  with negative lookbehinds to exclude e.g. `<` and `/` is not working to solve this.

Class names and component names are starting with the same prefix (e.g. `<q-input class="q-field--outlined">`.

**Comment by sndyuk** [comment]
@squareloop1

`(?<!\/|\<)q-[a-zA-Z-][a-zA-Z0-9-]*`
It won't be able to handle this kind of case:
```
<
  q-input class="q-field--outlined"
>
```

> Also mangling html tags

Could you paste the snippet of the processed HTML?

**Comment by squareloop1** [comment]
My provided selector was an example.
The processed HTML looks like this:

```html
<n class="row items-center justify-evenly" data-v-84477034="">
  <m class="test-class test-test tw-p-8" modelvalue="test" outlined="" label="TestInput" data-v-84477034=""></m>
</n>
```

Where it should look like this (without this plugin):
```html
<main class="q-page row items-center justify-evenly" data-v-4bc9d7de="" style="min-height: 929px;"><label
      class="q-field row no-wrap items-start q-field--outlined q-input q-field--float q-field--labeled test-class test-test tw-p-8"
      for="f_c604a073-c3bb-40b0-89a6-d951f7f91f04" data-v-4bc9d7de=""><!---->
      <div class="q-field__inner relative-position col self-stretch">
        <div class="q-field__control relative-position row no-wrap" tabindex="-1">
          <div class="q-field__control-container col relative-position row no-wrap q-anchor--skip"><input
            class="q-field__native q-placeholder" tabindex="0" aria-label="TestInput"
            id="f_c604a073-c3bb-40b0-89a6-d951f7f91f04" type="text"
            data-cip-id="f_c604a073-c3bb-40b0-89a6-d951f7f91f04">
            <div class="q-field__label no-pointer-events absolute ellipsis">TestInput</div><!----></div>
        </div><!----></div><!----></label>
    </main>
```

The unprocessed Vue SFC template for this part looks like this:
```html
<q-page class="row items-center justify-evenly">
  <q-input class="test-class test-test tw-p-8" v-model="test" outlined label="TestInput" />
</q-page>
```

As you can see in the unprocessed vue template there is not yet any class with a `q-` prefix but there are component tags having a similar scheme. After components are compiled they are normal html tags and classes.

**Comment by sndyuk** [comment]
@squareloop1 I see. It looks like the issue with the plugin order. Do you use Webpack 5?
If you can provide the minimum code(package.json, webpack.config.js, some Vue code) to reproduce it, it would be helpful.

**Comment by squareloop1** [comment]
Yes I am using webpack 5 via Quasar CLI. I'll try to create a minimum reproduction for you. Thanks for the very quick response to this issue and happy holidays!

**Comment by squareloop1** [comment]
I've created a minimal reproduction initialized with quasar-cli (similar to vue-cli): https://github.com/squareloop1/mangle-plugin-html-tag-reproduction

You can find the plugin configuration in `quasar.conf.js` at `extendWebpack(cfg) { ... }`.

To see the issue run `npm install` and `npm run dev` (development mode) or `npm run serve` (production mode).

I don't know if you are familiar with quasar. Quasar uses webpack 5 under the hood. Webpack configuration is freely customizable and extendable via quasar.conf.js. You can see the complete webpack config with `npx quasar inspect`.

**Comment by sndyuk** [comment]
@squareloop1 Thanks! 
I've investigated a bit but this is really mysterious. 
I can't find who replace `<div>` tag with `<foo>`(which is generated by the plugin). It should not happen in my understanding 🤔

**Comment by sndyuk** [comment]
I found the cause but I'm not sure it can be solved.

The plugin brokes the Vue naming conversion mechanism, like "q-btn" matches "QBtn" so that <q-btn> node can be compiled to <div>.
But the plugin replaces the "q-btn" to foo(e.g. `a`) so it won't match.
![image](https://user-images.githubusercontent.com/615630/147544056-141290a2-9bbd-4464-8d5f-c052bec7a3c6.png)

**Comment by squareloop1** [comment]
Interesting. I wonder if the same happens when using vue-cli with e.g. Vuetify (which uses a similar style with component tag names and class names). I will look into this some more too.

**Comment by squareloop1** [comment]
It indeed is the same issue with vue-cli and Vuetify: https://github.com/squareloop1/mangle-plugin-html-tag-vuetify. I suspect every major Vue framework will have issues with this plugin as they all have a similar scheme (html component tags and css class naming).

So far I know of quasar, vuetify and buefy (bulma).

**Comment by squareloop1** [comment]
I've found that this plugin seems to ignore / overwrite any minification done. So this plugin leaves me with unminified CSS files. Maybe thats related to this issue somehow.

**Comment by sndyuk** [comment]
@squareloop1 I think there is no way to integrate it with a CSS class managed by Vue.

> Could we exclude html tags from mangling somehow and only mangle stuff in the class="..." attributes?

It might be impossible since the class attributes can be modified by JS code(e.g. `tag.class = 'q-btn--hide'`) so we need to replace that JS code as well. Also, it's allowed to use the same value on id and class attribute.

> Seems like removing the third parameter from this line fixes this minifcation issue:

Thanks! I'll fix it.

**Comment by squareloop1** [comment]
> It might be impossible since the class attributes can be modified by JS code(e.g. tag.class = 'q-btn--hide') so we need to replace that JS code as well. Also, it's allowed to use the same value on id and class attribute.

Yes, I've came to the same conclusion. Theres too much dynamically generated so there is probably no way of knowing the exact classes to replace. Its working fine for pure CSS frameworks like tailwind with a prefix though.

I guess we can close this issue.
