### ISSUE TITLE
ReferenceError: Compilation is not defined

### ISSUE THREAD

**Issue by IRediTOTO** [sndyuk/mangle-css-class-webpack-plugin#39]
Hi, I got this error with newest version. Can you please take a look? 
`ReferenceError: Compilation is not defined`
`node_modules\mangle-css-class-webpack-plugin\lib\plugin.js:22:18`

**Comment by sndyuk** [comment]
@IRediTOTO Oh, 5.0.6 includes WIP code 😢  I've just released 5.0.7. Please use the latest one.
