### ISSUE TITLE
The first class after a back tick is not being obfuscated

### ISSUE THREAD

**Issue by raguila8** [sndyuk/mangle-css-class-webpack-plugin#43]
Hello,
I am using this plugin for my next.js project. The plugin seems to run twice; once for server-side and once for client-side. However, the server side (initial page load) obfuscation breaks when there is a class after a back tick. For example, in the following:
```jsx
<article className={`tw-py-8 sm:tw-flex xl:tw-items-center ${index > 0 ? 'tw-border-t' : 'lg:tw-border-t-0'}`}>
...
</article>
```
the `tw-py-8` class will not be obfuscated and the output HTML will look something like this:
```html
<article class="tw-py-8 nj um sm ul">
...
</article>
```
This happens for every class that is next to a back tick. I managed to solve the problem by changing the regex for `html` and `js` files in the `optimizer.js` file of the plugin (line 24) to:
```javascript
} else if (file.match(/.+\.js.*$/) || file.match(/.+\.html.*$/)) {
  classnameRegex = new RegExp(`["'\`.\\\s](${opts.classNameRegExp})`, 'g');
}
```
I just included a back tick in the regex to allow back ticks as prefix as well. 

What I don't understand is why it worked for the client-side version. That is, on the initial page load the obfuscation was broken, but when I navigated to other pages the classes were properly obfuscated. 

Hope this makes sense.

**Comment by sndyuk** [comment]
Thanks! Backtick should be fine as a literal delimiter. I've merged the p/r. 

> What I don't understand is why it worked for the client-side version. That is, on the initial page load the obfuscation was broken, but when I navigated to other pages the classes were properly obfuscated.

I'm still not sure the cause of the issue though...
