### ISSUE TITLE
not working  obfuscates 

### ISSUE THREAD

**Issue by aliakbarmotallebi** [sndyuk/mangle-css-class-webpack-plugin#54]
There seems to be a problem with the configuration
please help
I will correct the webpack

**Comment by aliakbarmotallebi** [comment]
Similar to this page:

https://portfolio-tailwind.preview.uideck.com/demos/personal/

**Comment by sndyuk** [comment]
@aliakbarmotallebi Could you elaborate on it and re-open the issue?
