### ISSUE TITLE
can you add the ability to blacklist / reserve certain classes?

### ISSUE THREAD

**Issue by vesper8** [sndyuk/mangle-css-class-webpack-plugin#7]
I'm running into some issues because I use font-awesome in my project and it includes a few classnames that are causing collisions with the mangled classnames, most notably the `fa` is widely used by font-awesome. There are also `fas` and `far` which are less likely to cause problems, but the `fa` is causing lots of problems as it carries a lot of style that is now being applied to elements as a result of using your plugin

Could we optionally pass an array of classes to reserve please?

Many thanks!

**Comment by sndyuk** [comment]
@vesper8 Added `reserveClassName` option. Please check if it works. Thanks!

```js
reserveClassName: ['fa', 'fas', 'far']
```

**Comment by vesper8** [comment]
This works perfectly!! Thanks so much!
