### ISSUE TITLE
ReferenceError: newClassMap is not defined

### ISSUE THREAD

**Issue by CanRau** [sndyuk/mangle-css-class-webpack-plugin#9]
I get 
```
ReferenceError: newClassMap is not defined
    at validate ([..]/node_modules/mangle-css-class-webpack-plugin/lib/optimizer.js:9:25)
```
https://github.com/sndyuk/mangle-css-class-webpack-plugin/blob/45de041825893d5f1c2d4d05cf9c88aa1728a9c5/lib/optimizer.js#L9

Uh now I understand, when setting `log: true` it works as it'll skip `validate` https://github.com/sndyuk/mangle-css-class-webpack-plugin/blob/45de041825893d5f1c2d4d05cf9c88aa1728a9c5/lib/optimizer.js#L8

And thanks for this amazing plugin 👏

**Comment by sndyuk** [comment]
@CanRau Thank you for reporting it!
I just fixed it. Please use the new version(v4.0.11).

**Comment by CanRau** [comment]
Amazing thank you 🙏
